services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
    - ./frontend/.docker.env
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
    - ./backend/.docker.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bloggy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh -c "python -m pytest ./tests -W ignore::DeprecationWarning"
    env_file:
    - ./backend/.docker.env
    depends_on:
      - backend
      - postgres
    profiles:
      # Prevents the default docker-compose command from starting this service
      - donotstart

volumes:
  postgres_data:
