services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
    - ./frontend/.docker.env
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
    - ./backend/.docker.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bloggy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
